// Aeropuertos IATA (~180) para el autocomplete de origen/destino/escala.
// Paridad con TT_AIRPORTS del HTML. Cobertura: hubs principales del mundo.

export type Airport = {
  code: string;
  city: string;
  name: string;
  country: string;
};

export const AIRPORTS: readonly Airport[] = [
  { code: 'GUA', city: 'Ciudad de Guatemala', name: 'La Aurora', country: 'Guatemala' },
  { code: 'CDMX', city: 'Ciudad de México', name: 'Múltiples (agrupado)', country: 'México' },
  { code: 'MEX', city: 'Ciudad de México', name: 'Benito Juárez', country: 'México' },
  { code: 'CUN', city: 'Cancún', name: 'Cancún Intl', country: 'México' },
  { code: 'GDL', city: 'Guadalajara', name: 'Miguel Hidalgo', country: 'México' },
  { code: 'MTY', city: 'Monterrey', name: 'Del Norte', country: 'México' },
  { code: 'SAL', city: 'San Salvador', name: 'Óscar A. Romero', country: 'El Salvador' },
  { code: 'TGU', city: 'Tegucigalpa', name: 'Toncontín', country: 'Honduras' },
  { code: 'SAP', city: 'San Pedro Sula', name: 'Ramón Villeda Morales', country: 'Honduras' },
  { code: 'MGA', city: 'Managua', name: 'Augusto C. Sandino', country: 'Nicaragua' },
  { code: 'SJO', city: 'San José', name: 'Juan Santamaría', country: 'Costa Rica' },
  { code: 'LIR', city: 'Liberia', name: 'Daniel Oduber', country: 'Costa Rica' },
  { code: 'PTY', city: 'Ciudad de Panamá', name: 'Tocumen Intl', country: 'Panamá' },
  { code: 'BZE', city: 'Belice', name: 'Philip Goldson', country: 'Belice' },
  { code: 'HAV', city: 'La Habana', name: 'José Martí', country: 'Cuba' },
  { code: 'SDQ', city: 'Santo Domingo', name: 'Las Américas', country: 'Rep. Dominicana' },
  { code: 'PUJ', city: 'Punta Cana', name: 'Punta Cana Intl', country: 'Rep. Dominicana' },
  { code: 'SJU', city: 'San Juan', name: 'Luis Muñoz Marín', country: 'Puerto Rico' },
  { code: 'KIN', city: 'Kingston', name: 'Norman Manley', country: 'Jamaica' },
  { code: 'NAS', city: 'Nasáu', name: 'Lynden Pindling', country: 'Bahamas' },
  { code: 'AUA', city: 'Oranjestad', name: 'Reina Beatrix', country: 'Aruba' },
  { code: 'CUR', city: 'Willemstad', name: 'Hato Intl', country: 'Curazao' },
  { code: 'BOG', city: 'Bogotá', name: 'El Dorado', country: 'Colombia' },
  { code: 'MDE', city: 'Medellín', name: 'José María Córdova', country: 'Colombia' },
  { code: 'CTG', city: 'Cartagena', name: 'Rafael Núñez', country: 'Colombia' },
  { code: 'CLO', city: 'Cali', name: 'Alfonso Bonilla Aragón', country: 'Colombia' },
  { code: 'UIO', city: 'Quito', name: 'Mariscal Sucre', country: 'Ecuador' },
  { code: 'GYE', city: 'Guayaquil', name: 'José Joaquín de Olmedo', country: 'Ecuador' },
  { code: 'LIM', city: 'Lima', name: 'Jorge Chávez', country: 'Perú' },
  { code: 'CUZ', city: 'Cusco', name: 'Alejandro Velasco Astete', country: 'Perú' },
  { code: 'LPB', city: 'La Paz', name: 'El Alto', country: 'Bolivia' },
  { code: 'VVI', city: 'Santa Cruz', name: 'Viru Viru', country: 'Bolivia' },
  { code: 'SCL', city: 'Santiago', name: 'Arturo Merino Benítez', country: 'Chile' },
  { code: 'EZE', city: 'Buenos Aires', name: 'Ministro Pistarini (Ezeiza)', country: 'Argentina' },
  { code: 'AEP', city: 'Buenos Aires', name: 'Aeroparque Jorge Newbery', country: 'Argentina' },
  { code: 'COR', city: 'Córdoba', name: 'Ingeniero Ambrosio Taravella', country: 'Argentina' },
  { code: 'MVD', city: 'Montevideo', name: 'Carrasco', country: 'Uruguay' },
  { code: 'ASU', city: 'Asunción', name: 'Silvio Pettirossi', country: 'Paraguay' },
  { code: 'CCS', city: 'Caracas', name: 'Simón Bolívar', country: 'Venezuela' },
  { code: 'GRU', city: 'São Paulo', name: 'Guarulhos', country: 'Brasil' },
  { code: 'GIG', city: 'Río de Janeiro', name: 'Galeão', country: 'Brasil' },
  { code: 'BSB', city: 'Brasilia', name: 'Presidente Juscelino Kubitschek', country: 'Brasil' },
  { code: 'SSA', city: 'Salvador', name: 'Deputado Luís Eduardo Magalhães', country: 'Brasil' },
  { code: 'MIA', city: 'Miami', name: 'Miami Intl', country: 'Estados Unidos' },
  { code: 'MCO', city: 'Orlando', name: 'Orlando Intl', country: 'Estados Unidos' },
  { code: 'FLL', city: 'Fort Lauderdale', name: 'Fort Lauderdale-Hollywood', country: 'Estados Unidos' },
  { code: 'JFK', city: 'Nueva York', name: 'John F. Kennedy', country: 'Estados Unidos' },
  { code: 'EWR', city: 'Nueva York', name: 'Newark Liberty', country: 'Estados Unidos' },
  { code: 'LGA', city: 'Nueva York', name: 'LaGuardia', country: 'Estados Unidos' },
  { code: 'LAX', city: 'Los Ángeles', name: 'Los Angeles Intl', country: 'Estados Unidos' },
  { code: 'SFO', city: 'San Francisco', name: 'San Francisco Intl', country: 'Estados Unidos' },
  { code: 'ORD', city: 'Chicago', name: "O'Hare Intl", country: 'Estados Unidos' },
  { code: 'DFW', city: 'Dallas', name: 'Dallas/Fort Worth', country: 'Estados Unidos' },
  { code: 'IAH', city: 'Houston', name: 'George Bush Intercontinental', country: 'Estados Unidos' },
  { code: 'ATL', city: 'Atlanta', name: 'Hartsfield-Jackson', country: 'Estados Unidos' },
  { code: 'BOS', city: 'Boston', name: 'Logan Intl', country: 'Estados Unidos' },
  { code: 'IAD', city: 'Washington D.C.', name: 'Washington Dulles', country: 'Estados Unidos' },
  { code: 'DCA', city: 'Washington D.C.', name: 'Ronald Reagan National', country: 'Estados Unidos' },
  { code: 'LAS', city: 'Las Vegas', name: 'Harry Reid Intl', country: 'Estados Unidos' },
  { code: 'SEA', city: 'Seattle', name: 'Seattle-Tacoma', country: 'Estados Unidos' },
  { code: 'DEN', city: 'Denver', name: 'Denver Intl', country: 'Estados Unidos' },
  { code: 'PHX', city: 'Phoenix', name: 'Sky Harbor', country: 'Estados Unidos' },
  { code: 'SAN', city: 'San Diego', name: 'San Diego Intl', country: 'Estados Unidos' },
  { code: 'AUS', city: 'Austin', name: 'Austin-Bergstrom', country: 'Estados Unidos' },
  { code: 'TPA', city: 'Tampa', name: 'Tampa Intl', country: 'Estados Unidos' },
  { code: 'HNL', city: 'Honolulú', name: 'Daniel K. Inouye', country: 'Estados Unidos' },
  { code: 'YYZ', city: 'Toronto', name: 'Pearson Intl', country: 'Canadá' },
  { code: 'YVR', city: 'Vancouver', name: 'Vancouver Intl', country: 'Canadá' },
  { code: 'YUL', city: 'Montreal', name: 'Pierre Elliott Trudeau', country: 'Canadá' },
  { code: 'YYC', city: 'Calgary', name: 'Calgary Intl', country: 'Canadá' },
  { code: 'LHR', city: 'Londres', name: 'Heathrow', country: 'Reino Unido' },
  { code: 'LGW', city: 'Londres', name: 'Gatwick', country: 'Reino Unido' },
  { code: 'MAN', city: 'Mánchester', name: 'Manchester Airport', country: 'Reino Unido' },
  { code: 'CDG', city: 'París', name: 'Charles de Gaulle', country: 'Francia' },
  { code: 'ORY', city: 'París', name: 'Orly', country: 'Francia' },
  { code: 'NCE', city: 'Niza', name: "Côte d'Azur", country: 'Francia' },
  { code: 'MAD', city: 'Madrid', name: 'Adolfo Suárez Barajas', country: 'España' },
  { code: 'BCN', city: 'Barcelona', name: 'El Prat', country: 'España' },
  { code: 'PMI', city: 'Palma de Mallorca', name: 'Son Sant Joan', country: 'España' },
  { code: 'AGP', city: 'Málaga', name: 'Costa del Sol', country: 'España' },
  { code: 'LIS', city: 'Lisboa', name: 'Humberto Delgado', country: 'Portugal' },
  { code: 'OPO', city: 'Oporto', name: 'Francisco Sá Carneiro', country: 'Portugal' },
  { code: 'FCO', city: 'Roma', name: 'Leonardo da Vinci (Fiumicino)', country: 'Italia' },
  { code: 'MXP', city: 'Milán', name: 'Malpensa', country: 'Italia' },
  { code: 'VCE', city: 'Venecia', name: 'Marco Polo', country: 'Italia' },
  { code: 'NAP', city: 'Nápoles', name: 'Capodichino', country: 'Italia' },
  { code: 'FRA', city: 'Fráncfort', name: 'Frankfurt am Main', country: 'Alemania' },
  { code: 'MUC', city: 'Múnich', name: 'Franz Josef Strauss', country: 'Alemania' },
  { code: 'BER', city: 'Berlín', name: 'Brandenburg', country: 'Alemania' },
  { code: 'AMS', city: 'Ámsterdam', name: 'Schiphol', country: 'Países Bajos' },
  { code: 'BRU', city: 'Bruselas', name: 'Brussels Airport', country: 'Bélgica' },
  { code: 'ZRH', city: 'Zúrich', name: 'Zurich Airport', country: 'Suiza' },
  { code: 'GVA', city: 'Ginebra', name: 'Geneva Airport', country: 'Suiza' },
  { code: 'VIE', city: 'Viena', name: 'Vienna Intl', country: 'Austria' },
  { code: 'CPH', city: 'Copenhague', name: 'Kastrup', country: 'Dinamarca' },
  { code: 'ARN', city: 'Estocolmo', name: 'Arlanda', country: 'Suecia' },
  { code: 'OSL', city: 'Oslo', name: 'Gardermoen', country: 'Noruega' },
  { code: 'HEL', city: 'Helsinki', name: 'Helsinki-Vantaa', country: 'Finlandia' },
  { code: 'DUB', city: 'Dublín', name: 'Dublin Airport', country: 'Irlanda' },
  { code: 'ATH', city: 'Atenas', name: 'Eleftherios Venizelos', country: 'Grecia' },
  { code: 'IST', city: 'Estambul', name: 'Estambul Airport', country: 'Turquía' },
  { code: 'SAW', city: 'Estambul', name: 'Sabiha Gökçen', country: 'Turquía' },
  { code: 'WAW', city: 'Varsovia', name: 'Chopin Airport', country: 'Polonia' },
  { code: 'PRG', city: 'Praga', name: 'Václav Havel', country: 'Rep. Checa' },
  { code: 'BUD', city: 'Budapest', name: 'Ferenc Liszt', country: 'Hungría' },
  { code: 'MOW', city: 'Moscú', name: 'Múltiples (agrupado)', country: 'Rusia' },
  { code: 'SVO', city: 'Moscú', name: 'Sheremétievo', country: 'Rusia' },
  { code: 'DXB', city: 'Dubái', name: 'Dubai Intl', country: 'Emiratos Árabes Unidos' },
  { code: 'AUH', city: 'Abu Dabi', name: 'Zayed Intl', country: 'Emiratos Árabes Unidos' },
  { code: 'DOH', city: 'Doha', name: 'Hamad Intl', country: 'Qatar' },
  { code: 'RUH', city: 'Riad', name: 'King Khalid Intl', country: 'Arabia Saudita' },
  { code: 'JED', city: 'Jeda', name: 'King Abdulaziz', country: 'Arabia Saudita' },
  { code: 'TLV', city: 'Tel Aviv', name: 'Ben Gurión', country: 'Israel' },
  { code: 'CAI', city: 'El Cairo', name: 'Cairo Intl', country: 'Egipto' },
  { code: 'CMN', city: 'Casablanca', name: 'Mohammed V', country: 'Marruecos' },
  { code: 'JNB', city: 'Johannesburgo', name: 'OR Tambo', country: 'Sudáfrica' },
  { code: 'CPT', city: 'Ciudad del Cabo', name: 'Cape Town Intl', country: 'Sudáfrica' },
  { code: 'NBO', city: 'Nairobi', name: 'Jomo Kenyatta', country: 'Kenia' },
  { code: 'LOS', city: 'Lagos', name: 'Murtala Muhammed', country: 'Nigeria' },
  { code: 'ADD', city: 'Adís Abeba', name: 'Bole Intl', country: 'Etiopía' },
  { code: 'DEL', city: 'Nueva Delhi', name: 'Indira Gandhi', country: 'India' },
  { code: 'BOM', city: 'Bombay', name: 'Chhatrapati Shivaji', country: 'India' },
  { code: 'BLR', city: 'Bangalore', name: 'Kempegowda', country: 'India' },
  { code: 'HKG', city: 'Hong Kong', name: 'Hong Kong Intl', country: 'Hong Kong' },
  { code: 'PEK', city: 'Pekín', name: 'Beijing Capital', country: 'China' },
  { code: 'PVG', city: 'Shanghái', name: 'Pudong', country: 'China' },
  { code: 'CAN', city: 'Cantón', name: 'Baiyun', country: 'China' },
  { code: 'ICN', city: 'Seúl', name: 'Incheon', country: 'Corea del Sur' },
  { code: 'NRT', city: 'Tokio', name: 'Narita', country: 'Japón' },
  { code: 'HND', city: 'Tokio', name: 'Haneda', country: 'Japón' },
  { code: 'KIX', city: 'Osaka', name: 'Kansai', country: 'Japón' },
  { code: 'TPE', city: 'Taipéi', name: 'Taoyuan', country: 'Taiwán' },
  { code: 'SIN', city: 'Singapur', name: 'Changi', country: 'Singapur' },
  { code: 'BKK', city: 'Bangkok', name: 'Suvarnabhumi', country: 'Tailandia' },
  { code: 'DMK', city: 'Bangkok', name: 'Don Mueang', country: 'Tailandia' },
  { code: 'HKT', city: 'Phuket', name: 'Phuket Intl', country: 'Tailandia' },
  { code: 'KUL', city: 'Kuala Lumpur', name: 'Kuala Lumpur Intl', country: 'Malasia' },
  { code: 'CGK', city: 'Yakarta', name: 'Soekarno-Hatta', country: 'Indonesia' },
  { code: 'DPS', city: 'Bali', name: 'Ngurah Rai', country: 'Indonesia' },
  { code: 'MNL', city: 'Manila', name: 'Ninoy Aquino', country: 'Filipinas' },
  { code: 'SGN', city: 'Ciudad Ho Chi Minh', name: 'Tan Son Nhat', country: 'Vietnam' },
  { code: 'HAN', city: 'Hanói', name: 'Noi Bai', country: 'Vietnam' },
  { code: 'SYD', city: 'Sídney', name: 'Kingsford Smith', country: 'Australia' },
  { code: 'MEL', city: 'Melbourne', name: 'Melbourne Airport', country: 'Australia' },
  { code: 'BNE', city: 'Brisbane', name: 'Brisbane Airport', country: 'Australia' },
  { code: 'AKL', city: 'Auckland', name: 'Auckland Airport', country: 'Nueva Zelanda' },
  { code: 'GEO', city: 'Georgetown', name: 'Cheddi Jagan', country: 'Guyana' },
  { code: 'POS', city: 'Puerto España', name: 'Piarco Intl', country: 'Trinidad y Tobago' },
  { code: 'BGI', city: 'Bridgetown', name: 'Grantley Adams', country: 'Barbados' },
  { code: 'SXM', city: 'Sint Maarten', name: 'Princess Juliana', country: 'San Martín' },
  { code: 'PLS', city: 'Providenciales', name: 'Providenciales Intl', country: 'Islas Turcas y Caicos' },
  { code: 'GCM', city: 'Georgetown', name: 'Owen Roberts', country: 'Islas Caimán' },
];

export function findAirport(code: string | null | undefined): Airport | undefined {
  if (!code) return undefined;
  return AIRPORTS.find((a) => a.code === code);
}
