// Nacionalidades para los pasaportes de los pasajeros.
//
// Son los códigos ISO 3166-1 alfa-3 — GTM, USA, MEX — que es lo que aparece
// impreso en el pasaporte y en la zona de lectura mecánica. NO son los de dos
// letras que usa el catálogo de países para el destino del viaje: un pasajero
// guatemalteco es GTM, no GT.
//
// Generado desde la lista oficial ISO 3166 cruzada con el catálogo de países
// del módulo, para que ambos hablen de los mismos 214 países.

export type Nacionalidad = {
  /** ISO 3166-1 alfa-3, el que va en el pasaporte. */
  code: string;
  /** ISO 3166-1 alfa-2, para cruzar con el catálogo de países. */
  alpha2: string;
  nombre: string;
};

export const NACIONALIDADES: readonly Nacionalidad[] = [
  { code: 'AFG', alpha2: 'AF', nombre: 'Afganistán' },
  { code: 'ALB', alpha2: 'AL', nombre: 'Albania' },
  { code: 'DEU', alpha2: 'DE', nombre: 'Alemania' },
  { code: 'AND', alpha2: 'AD', nombre: 'Andorra' },
  { code: 'AGO', alpha2: 'AO', nombre: 'Angola' },
  { code: 'ATG', alpha2: 'AG', nombre: 'Antigua y Barbuda' },
  { code: 'SAU', alpha2: 'SA', nombre: 'Arabia Saudita' },
  { code: 'DZA', alpha2: 'DZ', nombre: 'Argelia' },
  { code: 'ARG', alpha2: 'AR', nombre: 'Argentina' },
  { code: 'ARM', alpha2: 'AM', nombre: 'Armenia' },
  { code: 'ABW', alpha2: 'AW', nombre: 'Aruba' },
  { code: 'AUS', alpha2: 'AU', nombre: 'Australia' },
  { code: 'AUT', alpha2: 'AT', nombre: 'Austria' },
  { code: 'AZE', alpha2: 'AZ', nombre: 'Azerbaiyán' },
  { code: 'BHS', alpha2: 'BS', nombre: 'Bahamas' },
  { code: 'BGD', alpha2: 'BD', nombre: 'Bangladés' },
  { code: 'BRB', alpha2: 'BB', nombre: 'Barbados' },
  { code: 'BHR', alpha2: 'BH', nombre: 'Baréin' },
  { code: 'BEL', alpha2: 'BE', nombre: 'Bélgica' },
  { code: 'BLZ', alpha2: 'BZ', nombre: 'Belice' },
  { code: 'BEN', alpha2: 'BJ', nombre: 'Benín' },
  { code: 'BMU', alpha2: 'BM', nombre: 'Bermudas' },
  { code: 'BLR', alpha2: 'BY', nombre: 'Bielorrusia' },
  { code: 'BOL', alpha2: 'BO', nombre: 'Bolivia' },
  { code: 'BIH', alpha2: 'BA', nombre: 'Bosnia y Herzegovina' },
  { code: 'BWA', alpha2: 'BW', nombre: 'Botsuana' },
  { code: 'BRA', alpha2: 'BR', nombre: 'Brasil' },
  { code: 'BRN', alpha2: 'BN', nombre: 'Brunéi' },
  { code: 'BGR', alpha2: 'BG', nombre: 'Bulgaria' },
  { code: 'BFA', alpha2: 'BF', nombre: 'Burkina Faso' },
  { code: 'BDI', alpha2: 'BI', nombre: 'Burundi' },
  { code: 'BTN', alpha2: 'BT', nombre: 'Bután' },
  { code: 'CPV', alpha2: 'CV', nombre: 'Cabo Verde' },
  { code: 'KHM', alpha2: 'KH', nombre: 'Camboya' },
  { code: 'CMR', alpha2: 'CM', nombre: 'Camerún' },
  { code: 'CAN', alpha2: 'CA', nombre: 'Canadá' },
  { code: 'TCD', alpha2: 'TD', nombre: 'Chad' },
  { code: 'CHL', alpha2: 'CL', nombre: 'Chile' },
  { code: 'CHN', alpha2: 'CN', nombre: 'China' },
  { code: 'CYP', alpha2: 'CY', nombre: 'Chipre' },
  { code: 'VAT', alpha2: 'VA', nombre: 'Ciudad del Vaticano' },
  { code: 'COL', alpha2: 'CO', nombre: 'Colombia' },
  { code: 'COM', alpha2: 'KM', nombre: 'Comoras' },
  { code: 'PRK', alpha2: 'KP', nombre: 'Corea del Norte' },
  { code: 'KOR', alpha2: 'KR', nombre: 'Corea del Sur' },
  { code: 'CIV', alpha2: 'CI', nombre: 'Costa de Marfil' },
  { code: 'CRI', alpha2: 'CR', nombre: 'Costa Rica' },
  { code: 'HRV', alpha2: 'HR', nombre: 'Croacia' },
  { code: 'CUB', alpha2: 'CU', nombre: 'Cuba' },
  { code: 'CUW', alpha2: 'CW', nombre: 'Curazao' },
  { code: 'DNK', alpha2: 'DK', nombre: 'Dinamarca' },
  { code: 'DMA', alpha2: 'DM', nombre: 'Dominica' },
  { code: 'ECU', alpha2: 'EC', nombre: 'Ecuador' },
  { code: 'EGY', alpha2: 'EG', nombre: 'Egipto' },
  { code: 'SLV', alpha2: 'SV', nombre: 'El Salvador' },
  { code: 'ARE', alpha2: 'AE', nombre: 'Emiratos Árabes Unidos' },
  { code: 'ERI', alpha2: 'ER', nombre: 'Eritrea' },
  { code: 'SVK', alpha2: 'SK', nombre: 'Eslovaquia' },
  { code: 'SVN', alpha2: 'SI', nombre: 'Eslovenia' },
  { code: 'ESP', alpha2: 'ES', nombre: 'España' },
  { code: 'USA', alpha2: 'US', nombre: 'Estados Unidos' },
  { code: 'EST', alpha2: 'EE', nombre: 'Estonia' },
  { code: 'SWZ', alpha2: 'SZ', nombre: 'Esuatini' },
  { code: 'ETH', alpha2: 'ET', nombre: 'Etiopía' },
  { code: 'PHL', alpha2: 'PH', nombre: 'Filipinas' },
  { code: 'FIN', alpha2: 'FI', nombre: 'Finlandia' },
  { code: 'FJI', alpha2: 'FJ', nombre: 'Fiyi' },
  { code: 'FRA', alpha2: 'FR', nombre: 'Francia' },
  { code: 'GAB', alpha2: 'GA', nombre: 'Gabón' },
  { code: 'GMB', alpha2: 'GM', nombre: 'Gambia' },
  { code: 'GEO', alpha2: 'GE', nombre: 'Georgia' },
  { code: 'GHA', alpha2: 'GH', nombre: 'Ghana' },
  { code: 'GRD', alpha2: 'GD', nombre: 'Granada' },
  { code: 'GRC', alpha2: 'GR', nombre: 'Grecia' },
  { code: 'GRL', alpha2: 'GL', nombre: 'Groenlandia' },
  { code: 'GLP', alpha2: 'GP', nombre: 'Guadalupe' },
  { code: 'GUM', alpha2: 'GU', nombre: 'Guam' },
  { code: 'GTM', alpha2: 'GT', nombre: 'Guatemala' },
  { code: 'GIN', alpha2: 'GN', nombre: 'Guinea' },
  { code: 'GNQ', alpha2: 'GQ', nombre: 'Guinea Ecuatorial' },
  { code: 'GNB', alpha2: 'GW', nombre: 'Guinea-Bisáu' },
  { code: 'GUY', alpha2: 'GY', nombre: 'Guyana' },
  { code: 'HTI', alpha2: 'HT', nombre: 'Haití' },
  { code: 'HND', alpha2: 'HN', nombre: 'Honduras' },
  { code: 'HKG', alpha2: 'HK', nombre: 'Hong Kong' },
  { code: 'HUN', alpha2: 'HU', nombre: 'Hungría' },
  { code: 'IND', alpha2: 'IN', nombre: 'India' },
  { code: 'IDN', alpha2: 'ID', nombre: 'Indonesia' },
  { code: 'IRQ', alpha2: 'IQ', nombre: 'Irak' },
  { code: 'IRN', alpha2: 'IR', nombre: 'Irán' },
  { code: 'IRL', alpha2: 'IE', nombre: 'Irlanda' },
  { code: 'ISL', alpha2: 'IS', nombre: 'Islandia' },
  { code: 'CYM', alpha2: 'KY', nombre: 'Islas Caimán' },
  { code: 'MHL', alpha2: 'MH', nombre: 'Islas Marshall' },
  { code: 'SLB', alpha2: 'SB', nombre: 'Islas Salomón' },
  { code: 'TCA', alpha2: 'TC', nombre: 'Islas Turcas y Caicos' },
  { code: 'VGB', alpha2: 'VG', nombre: 'Islas Vírgenes Británicas' },
  { code: 'VIR', alpha2: 'VI', nombre: 'Islas Vírgenes de EE.UU.' },
  { code: 'ISR', alpha2: 'IL', nombre: 'Israel' },
  { code: 'ITA', alpha2: 'IT', nombre: 'Italia' },
  { code: 'JAM', alpha2: 'JM', nombre: 'Jamaica' },
  { code: 'JPN', alpha2: 'JP', nombre: 'Japón' },
  { code: 'JOR', alpha2: 'JO', nombre: 'Jordania' },
  { code: 'KAZ', alpha2: 'KZ', nombre: 'Kazajistán' },
  { code: 'KEN', alpha2: 'KE', nombre: 'Kenia' },
  { code: 'KGZ', alpha2: 'KG', nombre: 'Kirguistán' },
  { code: 'KIR', alpha2: 'KI', nombre: 'Kiribati' },
  { code: 'KWT', alpha2: 'KW', nombre: 'Kuwait' },
  { code: 'LAO', alpha2: 'LA', nombre: 'Laos' },
  { code: 'LSO', alpha2: 'LS', nombre: 'Lesoto' },
  { code: 'LVA', alpha2: 'LV', nombre: 'Letonia' },
  { code: 'LBN', alpha2: 'LB', nombre: 'Líbano' },
  { code: 'LBR', alpha2: 'LR', nombre: 'Liberia' },
  { code: 'LBY', alpha2: 'LY', nombre: 'Libia' },
  { code: 'LIE', alpha2: 'LI', nombre: 'Liechtenstein' },
  { code: 'LTU', alpha2: 'LT', nombre: 'Lituania' },
  { code: 'LUX', alpha2: 'LU', nombre: 'Luxemburgo' },
  { code: 'MAC', alpha2: 'MO', nombre: 'Macao' },
  { code: 'MKD', alpha2: 'MK', nombre: 'Macedonia del Norte' },
  { code: 'MDG', alpha2: 'MG', nombre: 'Madagascar' },
  { code: 'MYS', alpha2: 'MY', nombre: 'Malasia' },
  { code: 'MWI', alpha2: 'MW', nombre: 'Malaui' },
  { code: 'MDV', alpha2: 'MV', nombre: 'Maldivas' },
  { code: 'MLI', alpha2: 'ML', nombre: 'Malí' },
  { code: 'MLT', alpha2: 'MT', nombre: 'Malta' },
  { code: 'MAR', alpha2: 'MA', nombre: 'Marruecos' },
  { code: 'MTQ', alpha2: 'MQ', nombre: 'Martinica' },
  { code: 'MUS', alpha2: 'MU', nombre: 'Mauricio' },
  { code: 'MRT', alpha2: 'MR', nombre: 'Mauritania' },
  { code: 'MEX', alpha2: 'MX', nombre: 'México' },
  { code: 'FSM', alpha2: 'FM', nombre: 'Micronesia' },
  { code: 'MDA', alpha2: 'MD', nombre: 'Moldavia' },
  { code: 'MCO', alpha2: 'MC', nombre: 'Mónaco' },
  { code: 'MNG', alpha2: 'MN', nombre: 'Mongolia' },
  { code: 'MNE', alpha2: 'ME', nombre: 'Montenegro' },
  { code: 'MOZ', alpha2: 'MZ', nombre: 'Mozambique' },
  { code: 'MMR', alpha2: 'MM', nombre: 'Myanmar' },
  { code: 'NAM', alpha2: 'NA', nombre: 'Namibia' },
  { code: 'NRU', alpha2: 'NR', nombre: 'Nauru' },
  { code: 'NPL', alpha2: 'NP', nombre: 'Nepal' },
  { code: 'NIC', alpha2: 'NI', nombre: 'Nicaragua' },
  { code: 'NER', alpha2: 'NE', nombre: 'Níger' },
  { code: 'NGA', alpha2: 'NG', nombre: 'Nigeria' },
  { code: 'NOR', alpha2: 'NO', nombre: 'Noruega' },
  { code: 'NZL', alpha2: 'NZ', nombre: 'Nueva Zelanda' },
  { code: 'OMN', alpha2: 'OM', nombre: 'Omán' },
  { code: 'NLD', alpha2: 'NL', nombre: 'Países Bajos' },
  { code: 'PAK', alpha2: 'PK', nombre: 'Pakistán' },
  { code: 'PLW', alpha2: 'PW', nombre: 'Palaos' },
  { code: 'PSE', alpha2: 'PS', nombre: 'Palestina' },
  { code: 'PAN', alpha2: 'PA', nombre: 'Panamá' },
  { code: 'PNG', alpha2: 'PG', nombre: 'Papúa Nueva Guinea' },
  { code: 'PRY', alpha2: 'PY', nombre: 'Paraguay' },
  { code: 'PER', alpha2: 'PE', nombre: 'Perú' },
  { code: 'PYF', alpha2: 'PF', nombre: 'Polinesia Francesa' },
  { code: 'POL', alpha2: 'PL', nombre: 'Polonia' },
  { code: 'PRT', alpha2: 'PT', nombre: 'Portugal' },
  { code: 'PRI', alpha2: 'PR', nombre: 'Puerto Rico' },
  { code: 'QAT', alpha2: 'QA', nombre: 'Qatar' },
  { code: 'GBR', alpha2: 'GB', nombre: 'Reino Unido' },
  { code: 'CAF', alpha2: 'CF', nombre: 'República Centroafricana' },
  { code: 'CZE', alpha2: 'CZ', nombre: 'República Checa' },
  { code: 'COG', alpha2: 'CG', nombre: 'República del Congo' },
  { code: 'COD', alpha2: 'CD', nombre: 'República Democrática del Congo' },
  { code: 'DOM', alpha2: 'DO', nombre: 'República Dominicana' },
  { code: 'RWA', alpha2: 'RW', nombre: 'Ruanda' },
  { code: 'ROU', alpha2: 'RO', nombre: 'Rumania' },
  { code: 'RUS', alpha2: 'RU', nombre: 'Rusia' },
  { code: 'WSM', alpha2: 'WS', nombre: 'Samoa' },
  { code: 'BLM', alpha2: 'BL', nombre: 'San Bartolomé' },
  { code: 'KNA', alpha2: 'KN', nombre: 'San Cristóbal y Nieves' },
  { code: 'SMR', alpha2: 'SM', nombre: 'San Marino' },
  { code: 'MAF', alpha2: 'MF', nombre: 'San Martín' },
  { code: 'VCT', alpha2: 'VC', nombre: 'San Vicente y las Granadinas' },
  { code: 'LCA', alpha2: 'LC', nombre: 'Santa Lucía' },
  { code: 'STP', alpha2: 'ST', nombre: 'Santo Tomé y Príncipe' },
  { code: 'SEN', alpha2: 'SN', nombre: 'Senegal' },
  { code: 'SRB', alpha2: 'RS', nombre: 'Serbia' },
  { code: 'SYC', alpha2: 'SC', nombre: 'Seychelles' },
  { code: 'SLE', alpha2: 'SL', nombre: 'Sierra Leona' },
  { code: 'SGP', alpha2: 'SG', nombre: 'Singapur' },
  { code: 'SXM', alpha2: 'SX', nombre: 'Sint Maarten' },
  { code: 'SYR', alpha2: 'SY', nombre: 'Siria' },
  { code: 'SOM', alpha2: 'SO', nombre: 'Somalia' },
  { code: 'LKA', alpha2: 'LK', nombre: 'Sri Lanka' },
  { code: 'ZAF', alpha2: 'ZA', nombre: 'Sudáfrica' },
  { code: 'SDN', alpha2: 'SD', nombre: 'Sudán' },
  { code: 'SSD', alpha2: 'SS', nombre: 'Sudán del Sur' },
  { code: 'SWE', alpha2: 'SE', nombre: 'Suecia' },
  { code: 'CHE', alpha2: 'CH', nombre: 'Suiza' },
  { code: 'SUR', alpha2: 'SR', nombre: 'Surinam' },
  { code: 'THA', alpha2: 'TH', nombre: 'Tailandia' },
  { code: 'TWN', alpha2: 'TW', nombre: 'Taiwán' },
  { code: 'TZA', alpha2: 'TZ', nombre: 'Tanzania' },
  { code: 'TJK', alpha2: 'TJ', nombre: 'Tayikistán' },
  { code: 'TLS', alpha2: 'TL', nombre: 'Timor Oriental' },
  { code: 'TGO', alpha2: 'TG', nombre: 'Togo' },
  { code: 'TON', alpha2: 'TO', nombre: 'Tonga' },
  { code: 'TTO', alpha2: 'TT', nombre: 'Trinidad y Tobago' },
  { code: 'TUN', alpha2: 'TN', nombre: 'Túnez' },
  { code: 'TKM', alpha2: 'TM', nombre: 'Turkmenistán' },
  { code: 'TUR', alpha2: 'TR', nombre: 'Turquía' },
  { code: 'TUV', alpha2: 'TV', nombre: 'Tuvalu' },
  { code: 'UKR', alpha2: 'UA', nombre: 'Ucrania' },
  { code: 'UGA', alpha2: 'UG', nombre: 'Uganda' },
  { code: 'URY', alpha2: 'UY', nombre: 'Uruguay' },
  { code: 'UZB', alpha2: 'UZ', nombre: 'Uzbekistán' },
  { code: 'VUT', alpha2: 'VU', nombre: 'Vanuatu' },
  { code: 'VEN', alpha2: 'VE', nombre: 'Venezuela' },
  { code: 'VNM', alpha2: 'VN', nombre: 'Vietnam' },
  { code: 'YEM', alpha2: 'YE', nombre: 'Yemen' },
  { code: 'DJI', alpha2: 'DJ', nombre: 'Yibuti' },
  { code: 'ZMB', alpha2: 'ZM', nombre: 'Zambia' },
  { code: 'ZWE', alpha2: 'ZW', nombre: 'Zimbabue' },
];

export function findNacionalidad(code: string | null | undefined): Nacionalidad | undefined {
  if (!code) return undefined;
  const c = code.toUpperCase();
  return NACIONALIDADES.find((n) => n.code === c);
}
